# -*- coding: utf-8 -*-
"""Data Science Livestream for Sharing 20210517.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SQ2oAg6nkFy3i0vs_RIasf3-AHt1NIqv
"""

print('Hello, Python')

10 + 4

from sklearn import datasets

iris = datasets.load_iris()

print(iris.DESCR)

features = iris.data

features

target = iris.target

target

iris.target_names

iris.target_names[2]

from sklearn.model_selection import train_test_split

features_train, features_test, target_train, target_test = train_test_split(features, target, train_size=.8)

features_train.shape

features_test.shape

target_train.shape

target_test.shape

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)

model.fit(features_train, target_train)

model.predict(features_test)

model.predict_proba(features_test)

model.score(features_test, target_test)

